const wordCode = [
  ["eocf", "hello", "word"],
  ["mpc;", "world", "noun"],
  ["n.", "the", "word"],
  ["gj", "at", "word"],
  ["nop", "there", "word"],
  ["d.a", "some", "word"],
  ["aqb", "my", "word"],
  [".k", "of", "word"],
  ["", "be", "word"],
  ["", "use"],
  ["", "her", "word"],
  ["", "than", "word"],
  ["", "and", "word"],
  ["", "this", "word"],
  ["", "an", "word"],
  ["", "would", "word"],
  ["", "first", "word"],
  ["", "a", "word"],
  ["", "have"],
  ["", "each", "word"],
  ["", "make"],
  ["", "water"],
  ["", "to", "word"],
  ["", "from", "word"],
  ["", "which", "word"],
  ["", "like", "word"],
  ["", "been", "word"],
  ["", "in", "word"],
  ["", "or", "word"],
  ["", "she", "word"],
  ["", "him", "word"],
  ["", "call"],
  ["", "is"],
  ["", "one"],
  ["", "do"],
  ["", "into"],
  ["", "who"],
  ["", "you"],
  ["", "had"],
  ["", "how"],
  ["", "time"],
  ["", "oil"],
  ["", "that"],
  ["", "by"],
  ["", "their"],
  ["", "has"],
  ["", "its"],
  ["", "it"],
  ["", "word"],
  ["", "if"],
  ["", "look"],
  ["", "now"],
  ["", "he"],
  ["", "but"],
  ["", "will"],
  ["", "two"],
  ["", "find"],
  ["", "was"],
  ["", "not"],
  ["", "up"],
  ["", "more"],
  ["", "long"],
  ["", "for"],
  ["", "what"],
  ["", "other"],
  ["", "write"],
  ["", "down"],
  ["", "on"],
  ["", "all"],
  ["", "about"],
  ["", "go"],
  ["", "day"],
  ["", "are"],
  ["", "were"],
  ["", "out"],
  ["", "see"],
  ["", "did"],
  ["", "as"],
  ["", "we"],
  ["", "many"],
  ["", "number"],
  ["", "get"],
  ["", "with"],
  ["", "when"],
  ["", "then"],
  ["", "no"],
  ["", "come"],
  ["", "his"],
  ["", "your"],
  ["", "them"],
  ["", "way"],
  ["", "made"],
  ["", "they"],
  ["", "can"],
  ["", "these"],
  ["", "could"],
  ["", "may"],
  ["", "I"],
  ["", "said"],
  ["", "so"],
  ["", "people"],
  ["", "part"],
];
