const wordCode = [
  ["1", "&#9;"],
  ["eocf", "hello"],
  ["mpc;", "world", "noun"],
  ["n.", "the"],
  ["gj", "at"],
  ["nop", "there"],
  ["d.a", "some"],
  ["aqb", "my"],
  [".k", "of"],
  ["[x", "be"],
  ["bzr", "use"],
  ["ep", "her"],
  ["nol", "than"],
  ["ol;", "and"],
  ["nid", "this"],
  ["gl", "an"],
  ["mb;", "would"],
  ["'pcj", "first"],
  ["ob", "a"],
  ["egk", "have"],
  ["xu", "each"],
  ["aobh", "make", "verb"],
  ["mqjp", "water", "noun"],
  ["nz", "to"],
  ["'p.a", "from"],
  ["miu", "which"],
  ["cqbh", "like"],
  ["[il", "been"],
  ["il", "in"],
  ["fp", "or"],
  [",x", "she"],
  ["eia", "him"],
  ["hqc", "call"],
  ["ir", "is"],
  ["m.l", "one"],
  [";z", "do"],
  ["iljz", "into"],
  ["ez", "who"],
  ["bz", "you"],
  ["eg;", "had"],
  ["egm", "how"],
  ["jqba", "time", "noun"],
  ["fbc", "oil"],
  ["ngj", "that"],
  ["[qb", "by"],
  ["nop", "their"],
  ["egr", "has"],
  ["ijd", "its"],
  ["ij", "it"],
  ["mp;", "word"],
  ["i'", "if"],
  ["cbh", "look"],
  ["lgm", "now"],
  ["ex", "he"],
  ["[.j", "but"],
  ["mic", "will"],
  ["jz", "two"],
  ["'qbl;", "find"],
  ["m.r", "was"],
  ["lqj", "not"],
  [".v", "up"],
  ["aop", "more"],
  ["cqlt", "long"],
  ["'fp", "for"],
  ["m.j", "what"],
  [".np", "other"],
  [".npr", "others"],
  ["pqbj", "write"],
  [";gml", "down"],
  ["ql", "on"],
  ["qc", "all"],
  [".[gmj", "about"],
  ["tf", "go"],
  [";ob", "day"],
  ["qp", "are"],
  ["mp", "were"],
  ["gmj", "out"],
  ["dx", "see"],
  [";i;", "did"],
  ["gr", "as"],
  ["mx", "we"],
  ["aolx", "many"],
  ["l.a[p", "number", "noun"],
  ["toj", "get"],
  ["min", "with"],
  ["mol", "when"],
  ["nol", "then"],
  ["lf", "no"],
  ["h.a", "come"],
  ["eir", "his"],
  ["bop", "your"],
  ["noa", "them"],
  ["mob", "way"],
  ["aov;", "made"],
  ["nob", "they"],
  ["hgl", "can"],
  ["nxr", "these"],
  ["hb;", "could"],
  ["aob", "may"],
  ["qb", "I"],
  ["do;", "said"],
  ["df", "so"],
  ["vxve", "people", "noun"],
  ["vqpj", "part"],
  ["agmd", "mouse", "noun"],
  ["hgj", "cat", "noun"],
  ["toba", "game", "noun"],
  ["dgl;", "sand", "noun"],
  ["'obd", "face", "noun"],
  ["qcpo;x", "already"],
  [".", "a"]
];
